name: "Sticky Pull Request Comment"
description: "Create comment on pull request, if exists update that comment."
author: "marocchino"
inputs:
  header:
    description: "Header to determine if the comment is to be updated, not shown on screen. It can be used when you want to add multiple comments independently at the same time."
    required: false
  append:
    description: "Indicate if new comment messages should be appended to previous comment message. Only `true` is allowed. Just skip this item when you don't need it."
    required: false
  recreate:
    description: "Indicate if previous comment should be removed before creating a new comment. Only `true` is allowed. Just skip this item when you don't need it."
    required: false
  delete:
    description: "delete the previously created comment. Only `true` is allowed. Just skip this item when you don't need it."
    required: false
  message:
    description: "comment message"
    required: false
  path:
    description: "path to file containing comment message"
    required: false
  number:
    description: "pull request number for push event"
    required: false
  repo:
    description: "other repo name limited use on github enterprise. If not set, the current repo is used by default. Note that When you trying changing a repo, be aware that GITHUB_TOKEN should also use that repo's."
    required: false
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to ${{ github.token }}.'
    default: '${{ github.token }}'
runs:
  using: "node12"
  main: "dist/index.js"
