name: Comment on Pull Request
on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: FromPR
          message: |
            Test ${{ github.sha }} is successfully ended.
            This is message from PR.
